export const TYPES = {
  USER_LOADING: 'USER_LOADING',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_WITH_GOOGLE: 'LOGIN_USER_WITH_GOOGLE',
  SET_USER: 'SET_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  USER_ERRORS: 'USER_ERRORS',
  RELOAD_USER: 'RELOAD_USER',
};
