export const TYPES = {
  CART_LOADING: 'CART_LOADING',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  GET_CART: 'GET_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_FROM_CART_ONE_ITEM: 'REMOVE_FROM_CART_ONE_ITEM',
  TO_PAY: 'TO_PAY',
  ON_SUCCESS_BUY: 'ON_SUCCESS_BUY',
  CLEAR_CART: 'CLEAR_CART',
  ERRORS: 'ERRORS',
};
